improved logging

diff --git a/templates/reposync/reposync.erb b/templates/reposync/reposync.erb
--- a/templates/reposync/reposync.erb
+++ b/templates/reposync/reposync.erb
@@ -6,19 +6,19 @@ exec > <%= @logdir %>/<%= @repo_id %>.log 2>&1
 
 if [ -z "<%= @repo_path %>" ];
 then
-  echo "incorrect repo_path"
+  echo "$(date "+%Y-%m-%d %H:%M:%S") incorrect repo_path"
   exit 1
 fi
 
 if [ "<%= @repo_path %>" = "/" ];
 then
-  echo "root not allowed as repo_path"
+  echo "$(date "+%Y-%m-%d %H:%M:%S") root not allowed as repo_path"
   exit 1
 fi
 
 if [[ "<%= @repo_path %>" != /* ]];
 then
-  echo "error, repopath is not an absolute path"
+  echo "$(date "+%Y-%m-%d %H:%M:%S") error, repopath is not an absolute path"
   exit 1
 fi
 
@@ -30,7 +30,7 @@ while [ -f "/var/run/yum.pid" ];
 do
   if [ "$COUNT" -ge "100" ];
   then
-    echo "too many iterations waiting for yum.pid, aborting"
+    echo "$(date "+%Y-%m-%d %H:%M:%S") too many iterations waiting for yum.pid, aborting"
     exit 1
   fi
   sleep ${RANDOM:0:2}
@@ -55,3 +55,12 @@ reposync  -l\
           --download-metadata \
           <%- end -%>
           --download_path=<%= @repo_path%>
+
+if [ $? -eq 0 ];
+then
+  echo "$(date "+%Y-%m-%d %H:%M:%S") SUCCESS"
+  exit 0
+else
+  echo "$(date "+%Y-%m-%d %H:%M:%S") FAILED"
+  exit 1
+fi
