added creterepo to reposync

diff --git a/templates/reposync/reposync.erb b/templates/reposync/reposync.erb
--- a/templates/reposync/reposync.erb
+++ b/templates/reposync/reposync.erb
@@ -66,13 +66,24 @@ reposync  -l\
           <%- if @quiet -%>
           --quiet \
           <%- end -%>
-          --download_path=<%= @repo_path%>
+          --download_path=<%= @repo_path %>
 
 if [ $? -eq 0 ];
 then
-  echo "$(date "+%Y-%m-%d %H:%M:%S") SUCCESS"
-  exit 0
+  echo "$(date "+%Y-%m-%d %H:%M:%S") reposync SUCCESS"
+
+  createrepo -v  <%= @repo_path %> -g comps.xml
+
+  if [ $? -eq 0 ];
+  then
+    echo "$(date "+%Y-%m-%d %H:%M:%S") createrepo SUCCESS"
+    exit 0
+  else
+    echo "$(date "+%Y-%m-%d %H:%M:%S") createrepo FAILED"
+    exit 1
+  fi
+
 else
-  echo "$(date "+%Y-%m-%d %H:%M:%S") FAILED"
+  echo "$(date "+%Y-%m-%d %H:%M:%S") reposync FAILED"
   exit 1
 fi
